# Generated by Django 4.1.4 on 2022-12-10 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_number', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Employee number')),
                ('first_name', models.CharField(default='', max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(default='', max_length=100, verbose_name='Last name')),
                ('slug', models.SlugField(max_length=152)),
                ('gender', models.CharField(choices=[('N', 'No answer'), ('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='N', max_length=1, verbose_name='Gender')),
                ('hire_date', models.DateField(blank=True, verbose_name='Hire date')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, verbose_name='Salary')),
                ('remark', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['hire_date', 'last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Responsibility',
            fields=[
                ('responsibility_name', models.CharField(max_length=150, primary_key=True, serialize=False, verbose_name='Responsibility')),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('rank', models.PositiveSmallIntegerField(blank=True, default=1, unique=True, verbose_name='Rank')),
                ('description', models.TextField(verbose_name='Description')),
                ('minimum_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, verbose_name='Minimum salary')),
                ('maximum_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, verbose_name='Maximum salary')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_title', models.CharField(max_length=200, verbose_name='Work title')),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('begin', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Begin')),
                ('expected_duration', models.DurationField(blank=True, verbose_name='Expected duration')),
                ('end', models.DateTimeField(blank=True, verbose_name='End')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('done', models.BooleanField(default=False, verbose_name='Done')),
            ],
            options={
                'ordering': ['-begin'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200, verbose_name='Task name')),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start time')),
                ('expected_duration', models.DurationField(blank=True, verbose_name='Expected time')),
                ('end_time', models.DateTimeField(blank=True, verbose_name='End time')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('done', models.BooleanField(default=False, verbose_name='Done')),
                ('belong_to_work', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tasks', to='employee_manager.work', verbose_name='Belong to work')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tasks', to='employee_manager.employee', verbose_name='Employee')),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='responsibilities',
            field=models.ManyToManyField(blank=True, to='employee_manager.responsibility', verbose_name='Responsibility'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['task_name'], name='employee_ma_task_na_4bf64a_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['last_name', 'first_name'], name='employee_ma_last_na_86746d_idx'),
        ),
    ]
